// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy53uOsbX3f0rbDiRwqef_08NIA1zI9Ks',
    appId: '1:391995009782:web:ed1054492c562005195ad7',
    messagingSenderId: '391995009782',
    projectId: 'flutter-fire-events',
    authDomain: 'flutter-fire-events.firebaseapp.com',
    storageBucket: 'flutter-fire-events.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5cdEWDooZdvrSmP1_xY3ftQs6PMarNE',
    appId: '1:391995009782:android:60989b08bf15d42e195ad7',
    messagingSenderId: '391995009782',
    projectId: 'flutter-fire-events',
    storageBucket: 'flutter-fire-events.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJp3fJn16vkHQINwe7dr6SFuAtNYGt1w',
    appId: '1:391995009782:ios:ca744e53528702e3195ad7',
    messagingSenderId: '391995009782',
    projectId: 'flutter-fire-events',
    storageBucket: 'flutter-fire-events.appspot.com',
    iosClientId: '391995009782-eojo47l9da8rig1qj5ft7qke5t51abl9.apps.googleusercontent.com',
    iosBundleId: 'com.popupbits.flutterEvents2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJp3fJn16vkHQINwe7dr6SFuAtNYGt1w',
    appId: '1:391995009782:ios:ca744e53528702e3195ad7',
    messagingSenderId: '391995009782',
    projectId: 'flutter-fire-events',
    storageBucket: 'flutter-fire-events.appspot.com',
    iosClientId: '391995009782-eojo47l9da8rig1qj5ft7qke5t51abl9.apps.googleusercontent.com',
    iosBundleId: 'com.popupbits.flutterEvents2023',
  );
}
